// Copyright 2015 Hajime Hoshi
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"io/ioutil"
	"fmt"
	"strings"
	"os"
)

const tmpl = `// Generated by createdefaultscript.go: DO NOT EDIT

module editor {
    export const defaultScripts: string[] = [
%s
    ];
}
`

func main() {
	scripts := []string{}
	for _, file := range os.Args[1:] {
		script, err := ioutil.ReadFile(file)
		if err != nil {
			panic(err)
		}
		scripts = append(scripts, string(script))
	}

	r := strings.NewReplacer(
		"\\", "\\\\",
		"\"", "\\\"",
		"'", "\\'",
		"\n", "\\n",
		"\r", "\\r",
		"\u2028", "\\u2028",
		"\u2029", "\\u2029")
	literals := []string{}
	for _, script := range scripts {
		literals = append(literals, "        \"" + r.Replace(script) + "\"")
	}
	fmt.Printf(tmpl, strings.Join(literals, ",\n"))
}
