// Copyright 2015 Hajime Hoshi
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"io/ioutil"
	"fmt"
	"strings"
	"os"
)

const tmpl = `// Generated by createdefaultscript.go: DO NOT EDIT

namespace mocks {
    export const LIB_D_TS: string = "%s";
}
`
var stringLiteralContentReplacer = strings.NewReplacer(
	"\\", "\\\\",
	"\"", "\\\"",
	"'", "\\'",
	"\n", "\\n",
	"\r", "\\r",
	"\u2028", "\\u2028",
	"\u2029", "\\u2029")

func toStringLiteral(s string) string {
	return stringLiteralContentReplacer.Replace(s)
}

func main() {
	script, err := ioutil.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	fmt.Printf(tmpl, toStringLiteral(string(script)));
}
